[package]
name = "testbed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.egui-inspect]
path = ".."

[dependencies]
rand = "0.8.5"
eframe = "0.29.0"
